"""The `/ectype` command for the agents that have one: where it goes, under what name, its text.

Three agents let a user add a slash command by dropping a file into a folder: Claude Code
(`~/.claude/commands/<name>.md`), Gemini CLI (`~/.gemini/commands/<name>.toml`) and Codex
(`~/.codex/prompts/<name>.md`). The file name is the command name, so "call it /bringmedasummary
instead of /ectype" is a matter of which name the file is written under. `ectype skill install`
writes all three from the templates beside this module, under the name in Settings → Agent skill
(`skill.command`) or the one given; `status` says what is installed; `remove` deletes only files
this module wrote and nobody edited since. Each carries a marker line, and since 2026-09-27 the
marker records the ectype version AND a hash of the text written, so the file itself says whether
anyone touched it:

    ours     the text is what `render()` produces now, written by this ectype
    stale    untouched since ectype wrote it (the text still matches its own hash), but from an older
             template, or current text under an older ectype's marker: `install` updates it like one
             of its own
    edited   the text no longer matches its hash: refused, never overwritten or deleted, unless
             `--force`, which keeps it as `<file>.bak-<stamp>` first
    foreign  no marker: somebody's own command

Comparing with the CURRENT template alone (the rule until then) called every untouched file
"edited" the moment a template changed, and ectype keeps one version number until it publishes, so
a plain install refused the user's own untouched files. A file with no hash (written before the
change, or copied from `integrations/`) keeps that older rule: ours when equal to the current text.

The templates ship inside the package (package data), so this works from a pip install and from
the single-file build alike. The copies under `integrations/` in the repository are the same text
rendered for the name `ectype`, kept for people who read the repository; a test keeps them equal.
"""
from __future__ import annotations

import hashlib
import os
import re
from datetime import datetime
from importlib.resources import files
from pathlib import Path

from .. import __version__

MARK = "generated by ectype skill install"
NAME = re.compile(r"[A-Za-z][A-Za-z0-9_-]{0,63}")          # used with fullmatch: `$` let a trailing newline through
# "(ectype 0.3.1, sha256 1a2b3c4d5e6f)"; the hash part is absent from files written before 2026-09-27
_STAMP = re.compile(re.escape(MARK) + r" \(ectype ([^,)]*)(?:, sha256 ([0-9a-f]{12}))?\)")
# `env`: the variable the agent itself reads for its config folder, and the sub-folder under it. When
# it is set the file goes there, because that is where the agent will look (the Codex adapter honours
# the same CODEX_HOME for the store). Gemini CLI 0.58 reads GEMINI_CLI_HOME as the HOME its `.gemini`
# folder lives under (`homedir()` → `getGlobalGeminiDir()` → `commands`), hence `.gemini/commands`.
AGENTS: dict[str, dict] = {
    "claude-code": {"label": "Claude Code", "dir": "~/.claude/commands", "env": ("CLAUDE_CONFIG_DIR", "commands"),
                    "file": "{name}.md", "template": "claude-code.md", "use": "/{name} <id> [options]"},
    "gemini-cli": {"label": "Gemini CLI", "dir": "~/.gemini/commands", "env": ("GEMINI_CLI_HOME", ".gemini/commands"),
                   "file": "{name}.toml", "template": "gemini-cli.toml", "use": "/{name} <id> [options]"},
    "codex": {"label": "Codex", "dir": "~/.codex/prompts", "env": ("CODEX_HOME", "prompts"),
              "file": "{name}.md", "template": "codex.md", "use": "/{name} <id> [options]  (or /prompts:{name})"},
}


def valid_name(name: str) -> str:
    """The name, or ValueError: a letter first, then letters, digits, `-` and `_`, at most 64."""
    if not isinstance(name, str) or not NAME.fullmatch(name):
        raise ValueError(f"skill.command {name!r}: a command name starts with a letter and has only letters, digits, - and _ (at most 64)")
    return name


def render(agent: str, name: str, stamp: bool = True) -> str:
    """The command file's text for `agent`, under `name`. `stamp` puts the ectype version and the
    text's hash into the marker line (`_stamped`), which `state` reads back from an INSTALLED file;
    the copies shipped under `integrations/` are rendered without it, so a version bump does not
    change them."""
    if agent not in AGENTS:
        raise KeyError(f"no skill template for {agent!r}; agents with a command folder: {', '.join(AGENTS)}")
    valid_name(name)
    text = (files(__package__) / AGENTS[agent]["template"]).read_text(encoding="utf-8")
    text = text.replace("__NAME__", name)
    return _stamped(text) if stamp else text


def _digest(text: str) -> str:
    """The hash a marker records: of the text with its marker stripped back to the bare MARK."""
    return hashlib.sha256(_normal(text).encode("utf-8")).hexdigest()[:12]


def _stamped(text: str) -> str:
    """`text` (with the bare MARK) with the version and its own hash written into the marker."""
    return text.replace(MARK, f"{MARK} (ectype {__version__}, sha256 {_digest(text)})", 1)


def folder(agent: str) -> Path:
    """The agent's command folder: under its own config variable when that is set, else the default."""
    spec = AGENTS[agent]
    var = spec.get("env")
    if var and os.environ.get(var[0]):
        return Path(os.path.expanduser(os.path.expandvars(os.environ[var[0]]))) / var[1]
    return Path(os.path.expanduser(spec["dir"]))


def path(agent: str, name: str) -> Path:
    return folder(agent) / AGENTS[agent]["file"].format(name=name)


def _normal(text: str) -> str:
    return _STAMP.sub(MARK, text).strip()


def state(agent: str, name: str) -> tuple[str, str | None]:
    """(state, version) of the command file for `agent` under `name`: `absent`, `ours`, `stale`,
    `edited` or `foreign` (see the module docstring). `version` is the ectype version in the marker."""
    p = path(agent, name)
    if not p.is_file():
        return "absent", None
    try:
        text = p.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return "foreign", None
    if MARK not in text:
        return "foreign", None
    m = _STAMP.search(text)
    ver = m.group(1) if m else None
    recorded = m.group(2) if m else None
    if _normal(text) == _normal(render(agent, name)):
        # the text is current, but a marker naming another ectype says an older one wrote it (F69):
        # untouched all the same, so install brings the marker up to date like any stale file
        return ("stale" if ver and ver != __version__ else "ours"), ver
    if recorded and _digest(text) == recorded:
        return "stale", ver                  # nobody touched it: an older template, not an edit
    return "edited", ver


def status(name: str, agents: list[str] | None = None) -> list[dict]:
    """Per agent: where the file would be, its `state`, and the booleans the pages and tests read
    (`installed`, `ours`, `stale`: untouched but from an older template, `edited`)."""
    out = []
    for agent in agents or list(AGENTS):
        spec = AGENTS[agent]
        p = path(agent, name)
        st, ver = state(agent, name)
        out.append({"agent": agent, "label": spec["label"], "path": str(p), "state": st, "installed": st != "absent",
                    "ours": st == "ours", "stale": st == "stale", "edited": st == "edited", "version": ver,
                    "use": spec["use"].format(name=name)})
    return out


def _keep_aside(p: Path) -> Path:
    bak = p.with_name(p.name + f".bak-{datetime.now():%Y%m%d-%H%M%S}")
    p.replace(bak)
    return bak


def install(name: str, agents: list[str] | None = None, force: bool = False) -> list[Path]:
    """Write the command file for each agent (all three by default).

    Every target is checked BEFORE any is written, so a refusal leaves nothing half-installed (it used
    to write the first agents, then stop at the third, orphaning the files it had written). A file
    without the marker is the user's own and is refused; a marked file that was edited since is refused
    unless `force`, which keeps it as `<file>.bak-<stamp>` first; a stale one (untouched, older
    template) is simply rewritten, like a current one."""
    valid_name(name)
    targets = agents or list(AGENTS)
    for agent in targets:
        st, _ = state(agent, name)
        p = path(agent, name)
        if st == "foreign":
            raise FileExistsError(f"{p} exists and was not written by ectype; pick another name or move that file")
        if st == "edited" and not force:
            raise FileExistsError(f"{p} was written by ectype and edited since; --force replaces it (the edited file is kept as .bak)")
    written: list[Path] = []
    for agent in targets:
        p = path(agent, name)
        if force and state(agent, name)[0] == "edited":
            _keep_aside(p)
        p.parent.mkdir(parents=True, exist_ok=True)
        tmp = p.with_name(p.name + ".tmp")
        tmp.write_text(render(agent, name), encoding="utf-8")
        os.replace(tmp, p)
        written.append(p)
    return written


def remove(name: str, agents: list[str] | None = None, force: bool = False) -> tuple[list[Path], list[Path]]:
    """Delete the command files ectype wrote under `name`. Returns (removed, kept): a file without the
    marker, or one edited since ectype wrote it, is kept and reported, never deleted (with `force` an
    edited one is moved to `<file>.bak-<stamp>` instead)."""
    removed: list[Path] = []
    kept: list[Path] = []
    for agent in agents or list(AGENTS):
        p = path(agent, name)
        st, _ = state(agent, name)
        if st == "absent":
            continue
        if st in ("ours", "stale"):          # ectype's own, untouched
            p.unlink()
            removed.append(p)
        elif st == "edited" and force:
            _keep_aside(p)
            removed.append(p)
        else:
            kept.append(p)
    return removed, kept
